### PR TITLE
fix: support traces without FCP

### LINKED ISSUE #6: LHError: NO_FCP
Hello

I have next html file:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Estimo Template</title>
  </head>
  <body>
    <script src="/Users/mbalabash/Documents/projects/estimo/example/lib/2kb.js"></script>
  </body>
</html>
```

And the next js code with puppeteer to capture chrome trace:
```js
async function createChromeTrace(urlToHtmlFile, pathToTraceFile, browserOptions) {
  const { _headless: headless, _timeout: timeout } = browserOptions

  const browser = await puppeteer.launch({ headless })
  const page = await browser.newPage()

  await page.tracing.start({ path: pathToTraceFile })
  try {
    await page.goto(urlToHtmlFile, { timeout })
  } catch (err) {
    handleSessionError(err, browser)
  }
  await page.tracing.stop()

  await browser.close()
  return pathToTraceFile
}
```

And when i run it, i got an error: 
```
LHError: NO_FCP
    at Function.compute (/Users/mbalabash/Documents/projects/estimo/node_modules/tracium/lib/trace-of-tab.js:101:38)
    at Function.compute (/Users/mbalabash/Documents/projects/estimo/node_modules/tracium/lib/main-thread-tasks.js:271:55)
    at Object.computeMainThreadTasks (/Users/mbalabash/Documents/projects/estimo/node_modules/tracium/index.js:13:36)
```

In trace file, sections with FP / FCP / FMP really not exists. 
I checked it few times. 

But i can't reproduce this error with remote lib: 
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Estimo Template</title>
  </head>
  <body>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
  </body>
</html>
```
And with next workaround it also works fine:
```js
async function createChromeTrace(urlToHtmlFile, pathToTraceFile, browserOptions) {
  const { _headless: headless, _timeout: timeout } = browserOptions

  const browser = await puppeteer.launch({ headless })
  const page = await browser.newPage()

  await page.tracing.start({ path: pathToTraceFile })
  try {
    await page.goto(urlToHtmlFile, { timeout })
    await page.waitFor(100) // <--
  } catch (err) {
    handleSessionError(err, browser)
  }
  await page.tracing.stop()

  await browser.close()
  return pathToTraceFile
}
```

**Questions**
1) Do you know why it happens?
2) Can you suggest more predictable solution or workaround?

### PR DESCRIPTION
**Pull request by aslushnikov**
Tracium asserts existance of FCP, but it's not necessary for
general-purpose tracing processing.

This patch removes assumptions about FCP and adds a test.

Fix #6

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+const fs = require('fs');
+const path = require('path');
+const util = require('util');
+const {TestRunner, Reporter, Matchers} = require('@pptr/testrunner');
```
Comment (patrickhulce) [inline test/test.js:4]: curious how this suits non-pptr use cases compared to jest/mocha :)

File: lib/trace-of-tab.js [hunk 2]
```diff
@@ -144,7 +138,6 @@ class TraceOfTab {
     const timestamps = {
       navigationStart: navigationStart.ts,
       firstPaint: getTimestamp(firstPaint),
-      firstContentfulPaint: firstContentfulPaint.ts,
```
Comment (patrickhulce) [inline lib/trace-of-tab.js:147]: not sure it makes sense to remove fcp from here if we're leaving in `firstMeaningfulPaint`, `firstPaint`, etc

can we just remove the `if (!firstContentfulPaint` line?

File: test/test.js [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+const testRunner = new TestRunner();
+const {describe, xdescribe, fdescribe} = testRunner;
+const {it, fit, xit} = testRunner;
+const {beforeAll, beforeEach, afterAll, afterEach} = testRunner;
+const {expect} = new Matchers();
+
+describe('Tracium tests', function() {
+  it('should work with no FCP', async () => {
+    const trace = await readJSON('no_fcp.trace.json');
+    expect(Tracium.computeMainThreadTasks(trace).length).toBeGreaterThan(1);
```
Comment (patrickhulce) [inline test/test.js:22]: ⚠️ long tangent ahead feel free to reply only if you have time :)

we have fights about this over in LH so I'm curious what your take is...

some people like to do something like `expect(Tracium.computeMainThreadTasks(trace).length).toMatchInlineSnapshot(452)`

others think it absurdly stretches the bounds of automatically updatable expectations

(`toMatchInlineSnapshot` is a jest automatically updatable inline golden file essentially if you're unfamiliar with the command)

between what you have here, `toEqual(<manually computed number>)`, and `toMatchInlineSnapshot(<autocomputed number>)` what wins in the mind of @aslushnikov and why :)

**Review by patrickhulce — COMMENTED** [review]
a few thoughts, but I could also LGTM

No matter what happens here I think we'll need to sort out a lot more cases similar to this in LH post I/O and do an update

File: lib/trace-of-tab.js (hunk 2 above)
Comment (aslushnikov) [reply lib/trace-of-tab.js:147]: All of those are not needed - they are dropped on the floor in Tracium. I didn't touch them since there's an implicit goal to stay close to lighthouse's original code.

> can we just remove the if (!firstContentfulPaint line?

There are a few places down there that assume that `firstContentfulPaint` is not null - I removed those as well.

Comment (patrickhulce) [reply lib/trace-of-tab.js:147]: should've just been the difference between using `getTimestamp` and `maybeGetTiming` but alright :)

**Review by patrickhulce — APPROVED** [review]
WFM

File: test/test.js (hunk 1 above)
Comment (aslushnikov) [reply test/test.js:4]: @patrickhulce We'll see :-) I like it because it has zero NPM dependencies.

It also has zero magic: no global object injections, no special executable that does something with your test file. Tests are just a node.js script - run with `node test/test.js`, debug with `node --inspect-brk test/test.js`.

File: lib/trace-of-tab.js (hunk 2 above)
Comment (aslushnikov) [reply lib/trace-of-tab.js:147]: Ah, who knew there's `maybeGetTiming`!..

File: test/test.js (hunk 3 above)
Comment (aslushnikov) [reply test/test.js:22]: @patrickhulce (I started writing an answer yesterday night but fall asleep)

> between what you have here, toEqual(<manually computed number>), and toMatchInlineSnapshot(<autocomputed number>) what wins in the mind of @aslushnikov and why :)

The `toEqual(<manual number>)` and `toMatchInlineSnapshot(<autocomputed number>)` are basically the same thing - once the test fails, an engineer will have to look into Tracium, than look into the test, and figure who's fault is this. 

Given how many tasks we have here (452?), debugging this test failure might be a tedious process! If we have a dozen of such tests, each asserting some exact number of tasks, than the **effort of maintaining and acting** on the test failures will accumulate quickly.

The decision to **accept** or to **not accept** this effort is defined by the level of investment into the project and the risks we want to mitigate. If we were to build a core module for rocket launching, we'd build and exhaustive test coverage to catch as much as possible. We'd be fine with all the noise we have from the tests - better safe than sorry! 

In real world, most project don't deal with that much risks. If tests are unreasonably strict, developers will get frustrated and will just rubber-stamp-pass them. These tests suck out all the fun and have no value!

So my rule of a thumb is to start small and build up test coverage according to the needs. This particular test is added to avoid regressions once Tracium is merged into LH - and it seems to be doing just enough for this goal :-)
